// <auto-generated />
using FinalPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalPractice.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20220420041227_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("FinalPractice.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentName")
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            AssignmentName = "Mission 1"
                        },
                        new
                        {
                            AssignmentId = 2,
                            AssignmentName = "Mission 2"
                        },
                        new
                        {
                            AssignmentId = 3,
                            AssignmentName = "Mission 3"
                        },
                        new
                        {
                            AssignmentId = 4,
                            AssignmentName = "Mission 4"
                        },
                        new
                        {
                            AssignmentId = 5,
                            AssignmentName = "Mission 5"
                        },
                        new
                        {
                            AssignmentId = 6,
                            AssignmentName = "Mission 6"
                        },
                        new
                        {
                            AssignmentId = 7,
                            AssignmentName = "Mission 7"
                        },
                        new
                        {
                            AssignmentId = 8,
                            AssignmentName = "Mission 8"
                        },
                        new
                        {
                            AssignmentId = 9,
                            AssignmentName = "Mission 9"
                        },
                        new
                        {
                            AssignmentId = 10,
                            AssignmentName = "Mission 10"
                        },
                        new
                        {
                            AssignmentId = 11,
                            AssignmentName = "Mission 11"
                        },
                        new
                        {
                            AssignmentId = 12,
                            AssignmentName = "Mission 12"
                        });
                });

            modelBuilder.Entity("FinalPractice.Models.StudentQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNetID")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionID");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FinalPractice.Models.StudentQuestion", b =>
                {
                    b.HasOne("FinalPractice.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
